// <auto-generated />
using System;
using Game_Manager_Elite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Game_Manager_Elite.Migrations.Apa
{
    [DbContext(typeof(ApaContext))]
    [Migration("20260822005752_RebuildScoreboardForFiveGameLayout")]
    partial class RebuildScoreboardForFiveGameLayout
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Game_Manager_Elite.Models.ApaMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayMatchPoints")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<int>("HomeMatchPoints")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlayoff")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("ApaMatches");
                });

            modelBuilder.Entity("Game_Manager_Elite.Models.ApaPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApaTeamId")
                        .HasColumnType("int");

                    b.Property<int>("EightBallSkillLevel")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NineBallSkillLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApaTeamId");

                    b.ToTable("ApaPlayers");
                });

            modelBuilder.Entity("Game_Manager_Elite.Models.ApaPlayerMatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApaMatchId")
                        .HasColumnType("int");

                    b.Property<int>("AwayDefensiveShots")
                        .HasColumnType("int");

                    b.Property<int>("AwayPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("AwayPointsEarned")
                        .HasColumnType("int");

                    b.Property<int>("AwaySkillLevel")
                        .HasColumnType("int");

                    b.Property<int>("GameNumber")
                        .HasColumnType("int");

                    b.Property<int>("HomeDefensiveShots")
                        .HasColumnType("int");

                    b.Property<int>("HomePlayerId")
                        .HasColumnType("int");

                    b.Property<int>("HomePointsEarned")
                        .HasColumnType("int");

                    b.Property<int>("HomeSkillLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApaMatchId");

                    b.HasIndex("AwayPlayerId");

                    b.HasIndex("HomePlayerId");

                    b.ToTable("ApaPlayerMatches");
                });

            modelBuilder.Entity("Game_Manager_Elite.Models.ApaTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DivisionNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Format")
                        .HasColumnType("int");

                    b.Property<string>("HostLocation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Session")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ApaTeams");
                });

            modelBuilder.Entity("Game_Manager_Elite.Models.ApaTeamStanding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApaTeamId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentRank")
                        .HasColumnType("int");

                    b.Property<string>("DivisionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchesLost")
                        .HasColumnType("int");

                    b.Property<int>("MatchesWon")
                        .HasColumnType("int");

                    b.Property<int>("Session")
                        .HasColumnType("int");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<int>("WeeksPlayed")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApaTeamId");

                    b.ToTable("ApaTeamStandings");
                });

            modelBuilder.Entity("Game_Manager_Elite.Models.ApaMatch", b =>
                {
                    b.HasOne("Game_Manager_Elite.Models.ApaTeam", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Game_Manager_Elite.Models.ApaTeam", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("Game_Manager_Elite.Models.ApaPlayer", b =>
                {
                    b.HasOne("Game_Manager_Elite.Models.ApaTeam", "Team")
                        .WithMany("Roster")
                        .HasForeignKey("ApaTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Game_Manager_Elite.Models.ApaPlayerMatch", b =>
                {
                    b.HasOne("Game_Manager_Elite.Models.ApaMatch", "ParentMatch")
                        .WithMany("PlayerMatches")
                        .HasForeignKey("ApaMatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Game_Manager_Elite.Models.ApaPlayer", "AwayPlayer")
                        .WithMany()
                        .HasForeignKey("AwayPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Game_Manager_Elite.Models.ApaPlayer", "HomePlayer")
                        .WithMany()
                        .HasForeignKey("HomePlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayPlayer");

                    b.Navigation("HomePlayer");

                    b.Navigation("ParentMatch");
                });

            modelBuilder.Entity("Game_Manager_Elite.Models.ApaTeamStanding", b =>
                {
                    b.HasOne("Game_Manager_Elite.Models.ApaTeam", "Team")
                        .WithMany()
                        .HasForeignKey("ApaTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Game_Manager_Elite.Models.ApaMatch", b =>
                {
                    b.Navigation("PlayerMatches");
                });

            modelBuilder.Entity("Game_Manager_Elite.Models.ApaTeam", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("Roster");
                });
#pragma warning restore 612, 618
        }
    }
}
